### ISSUE TITLE
c.JupyterHub.hub_connect_ip can't be a hostname with KubeIngressProxy

### ISSUE THREAD

**Issue by BerserkerTroll** [jupyterhub/kubespawner#116]
JupyterHub's documentation says that `hub_connect_ip` is "The ip or **hostname** for proxies and spawners to use for connecting to the Hub".
But when I tried to assign k8s service's hostname to the `c.JupyterHub.hub_connect_ip`, namely
```
c.JupyterHub.hub_connect_ip = 'jupyterhub.jupyterhub.svc.cluster.local'
```
I got this:
```
[I 2018-01-11 00:53:01.790 JupyterHub app:888] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[I 2018-01-11 00:53:01.875 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2018-01-11 00:53:01.876 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2018-01-11 00:53:02.294 alembic.runtime.migration migration:327] Running stamp_revision  -> 1cebaf56856c
[I 2018-01-11 00:53:06.257 JupyterHub reflector:129] watching for ingresses with label selector heritage=jupyterhub,component=singleuser-server,hub.jupyter.org/proxy-route=true in namespace jupyterhub
[I 2018-01-11 00:53:06.260 JupyterHub reflector:129] watching for services with label selector heritage=jupyterhub,component=singleuser-server,hub.jupyter.org/proxy-route=true in namespace jupyterhub
[I 2018-01-11 00:53:06.283 JupyterHub reflector:129] watching for endpoints with label selector heritage=jupyterhub,component=singleuser-server,hub.jupyter.org/proxy-route=true in namespace jupyterhub
[W 2018-01-11 00:53:06.286 JupyterHub app:972] No admin users, admin interface will be unavailable.
[W 2018-01-11 00:53:06.286 JupyterHub app:973] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-01-11 00:53:06.286 JupyterHub app:1000] Not using whitelist. Any authenticated user will be allowed.
[I 2018-01-11 00:53:06.334 JupyterHub app:1545] Hub API listening on http://0.0.0.0:8081/hub/
[W 2018-01-11 00:53:06.334 JupyterHub proxy:304] Adding missing default route
[I 2018-01-11 00:53:06.335 JupyterHub proxy:370] Adding default route for Hub: / => http://jupyterhub.jupyterhub.svc.cluster.local:8081
[E 2018-01-11 00:53:06.351 JupyterHub app:1637]
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1635, in launch_instance_async
        yield self.start()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1586, in start
        yield self.proxy.check_routes(self.users, self._service_map)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/proxy.py", line 366, in check_routes
        yield f
      File "/opt/conda/lib/python3.5/site-packages/kubespawner/proxy.py", line 152, in add_route
        kind='endpoints'
      File "/opt/conda/lib/python3.5/site-packages/kubespawner/proxy.py", line 132, in ensure_object
        body=body
      File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.5/site-packages/kubespawner/proxy.py", line 104, in asynchronize
        return method(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/apis/core_v1_api.py", line 6097, in create_namespaced_endpoints
        (data) = self.create_namespaced_endpoints_with_http_info(namespace, body, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/apis/core_v1_api.py", line 6187, in create_namespaced_endpoints_with_http_info
        collection_formats=collection_formats)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 335, in call_api
        _preload_content, _request_timeout)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
        _request_timeout=_request_timeout)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 393, in request
        body=body)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/rest.py", line 287, in POST
        body=body)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/rest.py", line 240, in request
        raise ApiException(http_resp=r)
    kubernetes.client.rest.ApiException: (422)
    Reason: Unprocessable Entity
    HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 11 Jan 2018 00:53:06 GMT', 'Content-Length': '540', 'Content-Type': 'application/json'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Endpoints \"jupyter--2f-route\" is invalid: subsets[0].addresses[0].ip: Invalid value: \"jupyterhub.jupyterhub.svc.cluster.local\": must be a valid IP address, (e.g. 10.9.8.7)","reason":"Invalid","details":{"name":"jupyter--2f-route","kind":"Endpoints","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"jupyterhub.jupyterhub.svc.cluster.local\": must be a valid IP address, (e.g. 10.9.8.7)","field":"subsets[0].addresses[0].ip"}]},"code":422}
```

So I had to use `socket.gethostbyname` to resolve hostname in the config.

**Comment by yuvipanda** [comment]
Thanks for the issue! It looks like the Kubernetes Endpoint object will always want an IP rather than DNS name. We'll find a place to document this somewhere!

**Comment by BerserkerTroll** [comment]
> We'll find a place to document this somewhere!

Ehm... you are not going to fix this, just document? I have thought that the possibility to use hostname is the requirement/contract JupyterHub puts on every Proxy implementation.

**Comment by yuvipanda** [comment]
It's a core requirement from Kubernetes that I don't think we can do anything to fix. I think we will probably just add to the docs in JupyterHub that hostnames might not be supported depending on the implementation.

**Comment by BerserkerTroll** [comment]
> I don't think we can do anything to fix

How about `gethostbyname`?

**Comment by yuvipanda** [comment]
I generally prefer not doing too much extra over what Kubernetes itself does. For example, gethostname is unlikely to resolve 'jupyterhub.jupyterhub.svc.cluster.local' if the hub is running outside k8s, for example. And inside Kubernetes, I would recommend setting hub_connect_ip to something like `os.environ['JUPYTERHUB_SERVICE_HOST']` (which is automatically populated) than using the hostname directly.

**Comment by BerserkerTroll** [comment]
> gethostname is unlikely to resolve 'jupyterhub.jupyterhub.svc.cluster.local' if the hub is running outside k8s

I meant using `gethostname` in KubeIngressProxy. It is unlikely that someone will try to use KubeIngressProxy outside k8s.

**Comment by yuvipanda** [comment]
We support running the hub process outside k8s if people want to, and folks do. I've opened https://github.com/jupyterhub/jupyterhub/pull/1615 to amend the docs.

**Comment by BerserkerTroll** [comment]
> We support running the hub process outside k8s if people want to

Ok, I see. I've thought that KubeIngressProxy is designed to be used only from the inside of the k8s.

**Comment by yuvipanda** [comment]
That's the recommended configuration, but enough people want to not run the hub process on k8s (and only use k8s for spawning) that we try to support it. Only the user pods need to run inside k8s, not the hub.

Regardless, I think matching kubernetes semantics directly is a good enough reason by itself.

**Comment by BerserkerTroll** [comment]
> gethostname is unlikely to resolve 'jupyterhub.jupyterhub.svc.cluster.local' if the hub is running outside k8s

I would like to return to this argument. I do not understand why someone will use cluser-local address for hub which is running outside k8s? The hub is either running inside k8s and then such a hostname is resolvable or it is running outside k8s and then  pointing `hub_connect_ip` to k8s cluster-local address is just incorrect and not because it is not resolvable.

**Comment by BerserkerTroll** [comment]
> I don't think we can do anything to fix

You can ask the k8s API server (in my case it is `/api/v1/namespaces/jupyterhub/services/jupyterhub-api`) and get the IP of the service.

**Comment by yuvipanda** [comment]
Going to close this for now.

**Comment by BerserkerTroll** [comment]
> Going to close this for now.

Not so fast, the bug is not fixed yet.
