### ISSUE TITLE
Pod spawns but is not detected by Hub

### ISSUE THREAD

**Issue by marcusianlevine** [jupyterhub/kubespawner#121]
I've deployed JupyterHub 0.8.1 with the latest commit of kubespawner using v0.4 of the Helm chart and custom Hub and singleuser images.

My singleuser pods seem to spawn successfully, yet are never detected as ready by the Hub.

My singleuser image does take a long time to pull (~7 minutes from pod creation to up-and-running on first pull) but I adjusted the `start_timeout` configuration to 10 minutes to handle that.

Eventually the spawn times out and throws 500, even though the singleuser notebook server says it is ready to go ~2 minutes before the timouet.

I thought that #88 might resolve this issue, but I tried deploying the latest commit from that PR and got the same behavior.

### Singleuser logs

```
/bin/bash: /opt/conda/envs/python2/lib/libtinfo.so.5: no version information available (required by /bin/bash)
Set username to: jovyan
usermod: no changes
Granting jovyan sudo access and appending /opt/conda/bin to sudo PATH
Executing the command: jupyterhub-singleuser --ip="0.0.0.0" --port=8888 --notebook-dir="/oedsshare"
[W 2018-01-20 01:57:37.446 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2018-01-20 01:57:38.371 SingleUserNotebookApp extension:53] JupyterLab beta preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2018-01-20 01:57:38.371 SingleUserNotebookApp extension:54] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2018-01-20 01:57:38.386 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.1
[I 2018-01-20 01:57:38.405 SingleUserNotebookApp notebookapp:1585] Serving notebooks from local directory: /oedsshare
[I 2018-01-20 01:57:38.405 SingleUserNotebookApp notebookapp:1585] 0 active kernels
[I 2018-01-20 01:57:38.405 SingleUserNotebookApp notebookapp:1585] The Jupyter Notebook is running at:
[I 2018-01-20 01:57:38.405 SingleUserNotebookApp notebookapp:1585] http://0.0.0.0:8888/user/mlevine4/
[I 2018-01-20 01:57:38.406 SingleUserNotebookApp notebookapp:1586] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

### Hub logs

```
 [I 2018-01-20 01:53:58.139 JupyterHub base:727] mlevine4 is pending spawn
[I 2018-01-20 01:53:58.152 JupyterHub log:122] 200 GET /hub/user/mlevine4/ (mlevine4@10.42.62.66) 10013.77ms
[I 2018-01-20 01:54:15.139 JupyterHub base:722] Pending spawn for mlevine4 didn't finish in 10.0 seconds
[I 2018-01-20 01:54:15.139 JupyterHub base:727] mlevine4 is pending spawn
[I 2018-01-20 01:54:15.147 JupyterHub log:122] 200 GET /hub/user/mlevine4/ (mlevine4@10.42.62.66) 10010.94ms
[I 2018-01-20 01:54:32.142 JupyterHub base:722] Pending spawn for mlevine4 didn't finish in 10.0 seconds

...more of the same...

[I 2018-01-20 01:55:23.143 JupyterHub base:727] mlevine4 is pending spawn
[I 2018-01-20 01:55:23.150 JupyterHub log:122] 200 GET /hub/user/mlevine4/ (mlevine4@10.42.62.66) 10009.77ms
[I 2018-01-20 01:55:40.147 JupyterHub base:722] Pending spawn for mlevine4 didn't finish in 10.0 seconds
[I 2018-01-20 01:55:40.147 JupyterHub base:727] mlevine4 is pending spawn
[I 2018-01-20 01:55:40.155 JupyterHub log:122] 200 GET /hub/user/mlevine4/ (mlevine4@10.42.62.66) 10011.86ms
[I 2018-01-20 01:55:57.144 JupyterHub base:722] Pending spawn for mlevine4 didn't finish in 10.0 seconds
[I 2018-01-20 01:55:57.145 JupyterHub base:727] mlevine4 is pending spawn
[I 2018-01-20 01:55:57.152 JupyterHub log:122] 200 GET /hub/user/mlevine4/ (mlevine4@10.42.62.66) 10010.82ms
[I 2018-01-20 01:56:14.144 JupyterHub base:722] Pending spawn for mlevine4 didn't finish in 10.0 seconds
[I 2018-01-20 01:56:14.144 JupyterHub base:727] mlevine4 is pending spawn
[I 2018-01-20 01:56:14.150 JupyterHub log:122] 200 GET /hub/user/mlevine4/ (mlevine4@10.42.62.66) 10009.26ms
[I 2018-01-20 01:56:31.150 JupyterHub base:722] Pending spawn for mlevine4 didn't finish in 10.0 seconds
[I 2018-01-20 01:56:31.150 JupyterHub base:727] mlevine4 is pending spawn
[I 2018-01-20 01:56:31.156 JupyterHub log:122] 200 GET /hub/user/mlevine4/ (mlevine4@10.42.62.66) 10012.94ms
[I 2018-01-20 01:56:48.143 JupyterHub base:722] Pending spawn for mlevine4 didn't finish in 10.0 seconds 
     
[E 2018-01-20 01:59:33.808 JupyterHub gen:914] Exception in Future &lt;tornado.concurrent.Future object at 0x7f6736e30e48&gt; after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
    tornado.gen.TimeoutError: Timeout 

...more of the same...
     
[E 2018-01-20 01:59:33.828 JupyterHub gen:914] Exception in Future &lt;tornado.concurrent.Future object at 0x7f6736e30e48&gt; after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
    tornado.gen.TimeoutError: Timeout
 [I 2018-01-20 01:59:33.835 JupyterHub base:722] Pending spawn for mlevine4 didn't finish in 10.0 seconds
[E 2018-01-20 01:59:33.875 JupyterHub user:427] Unhandled error starting mlevine4's server: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[E 2018-01-20 01:59:33.894 JupyterHub web:1591] Uncaught exception GET /hub/user/mlevine4/ (10.42.62.66)
    HTTPServerRequest(protocol='http', host='dev.jh.iq-toolkit.com', method='GET', uri='/hub/user/mlevine4/', version='HTTP/1.1', remote_ip='10.42.62.66', headers={'X-Forwarded-Host': 'dev.jh.iq-toolkit.com', 'Connection': 'close', 'X-Forwarded-For': '10.180.191.164,10.42.62.66', 'X-Forwarded-Proto': 'https,http', 'X-Forwarded-Port': '443,80', 'Cookie': 'jupyter-hub-token="2|1:0|10:1516331425|17:jupyter-hub-token|44:NmExNDA0NmVjNTdhNDE0ODhmNTczNDZjZTdkM2M3NWU=|5ffd38b8412c2e26cb105a2309c16d25eb0672bc23bcaadf6d758f9c5f21a949"; _ga=GA1.2.1812784613.1502156934', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Referer': 'https://dev.jh.iq-toolkit.com/hub/user/mlevine4/', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36', 'Upgrade-Insecure-Requests': '1', 'Cache-Control': 'max-age=0', 'Host': 'dev.jh.iq-toolkit.com'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 747, in get
        yield self.spawn_single_user(current_user)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 475, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/conda/lib/python3.6/site-packages/kubespawner/spawner.py", line 963, in start
        pod
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception  
 [E 2018-01-20 01:59:51.526 JupyterHub gen:914] Exception in Future &lt;tornado.concurrent.Future object at 0x7f6736e30d68&gt; after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/kubespawner/spawner.py", line 985, in start
        timeout=self.start_timeout
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-mlevine4 did not start in 600 seconds! 
```

**Comment by gweis** [comment]
Not sure what's going on .....

I probably would look into this exception:
`[E 2018-01-20 01:59:33.875 JupyterHub user:427] Unhandled error starting mlevine4's server: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

and that one:

```
2018-01-20 01:59:33.894 JupyterHub web:1591] Uncaught exception GET /hub/user/mlevine4/ (10.42.62.66)
    HTTPServerRequest(protocol='http', host='dev.jh.iq-toolkit.com', method='GET', uri='/hub/user/mlevine4/', version='HTTP/1.1', remote_ip='10.42.62.66', headers={'X-Forwarded-Host': 'dev.jh.iq-toolkit.com', 'Connection': 'close', 'X-Forwarded-For': '10.180.191.164,10.42.62.66', 'X-Forwarded-Proto': 'https,http', 'X-Forwarded-Port': '443,80', 'Cookie': 'jupyter-hub-token="2|1:0|10:1516331425|17:jupyter-hub-token|44:NmExNDA0NmVjNTdhNDE0ODhmNTczNDZjZTdkM2M3NWU=|5ffd38b8412c2e26cb105a2309c16d25eb0672bc23bcaadf6d758f9c5f21a949"; _ga=GA1.2.1812784613.1502156934', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Referer': 'https://dev.jh.iq-toolkit.com/hub/user/mlevine4/', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36', 'Upgrade-Insecure-Requests': '1', 'Cache-Control': 'max-age=0', 'Host': 'dev.jh.iq-toolkit.com'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 747, in get
        yield self.spawn_single_user(current_user)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 475, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/conda/lib/python3.6/site-packages/kubespawner/spawner.py", line 963, in start
        pod
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception  
```

I think the timeouts are just side effects of one of these two exceptions

looks a bit like there is something going wrong in `self.modify_pod_hook` or so

**Comment by marcusianlevine** [comment]
Thanks for taking a look @gweis 

So the bit I failed to disclose is that I had started testing the previously-working setup on a single-machine k8s cluster to save $$$ 😅  

You were right about the `Connection reset by peer` line — seems that the k8s API server was too unstable and started dropping connections randomly. I found the same error reported in the kube server logs.

I scaled back up to the recommended 3 node cluster and everything is back to normal...
