### ISSUE TITLE
When user login throw "No such file or directory: '/root/.kube/config'"

### ISSUE THREAD

**Issue by xuande** [jupyterhub/kubespawner#132]
```
2018-02-08T08:39:30.268052000Z [E 2018-02-08 08:39:30.012 JupyterHub web:1591] Uncaught exception GET /hub/home (172.17.18.1)
2018-02-08T08:39:30.268534000Z     HTTPServerRequest(protocol='http', host='10.110.18.88:30710', method='GET', uri='/hub/home', version='HTTP/1.1', remote_ip='172.17.18.1', headers={'Cache-Control': 'no-cache', 'Accept-Encoding': 'gzip, deflate', 'Postman-Token': '27b5f3b1-74dc-a04f-4e5f-756272d24f4a', 'X-Forwarded-For': '172.17.18.1', 'Remote_user': 'brent', 'Connection': 'close', 'X-Postman-Interceptor-Id': '66a52359-4107-c526-79a2-a263ba82d0be', 'X-Forwarded-Host': '10.110.18.88:30710', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36', 'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8', 'X-Forwarded-Port': '30710', 'Host': '10.110.18.88:30710', 'Content-Type': 'application/json', 'Cookie': 'jupyter-hub-token="2|1:0|10:1518079169|17:jupyter-hub-token|44:ZDUwMmJmNDk0MjQwNDhiNzg1OWUxMWFkZTExZDZlZjI=|5f82a72814673984088e67754be27e9e9a8d05f1a1bfb867ccdb3db9ce611eaa"', 'Accept': '*/*', 'X-Forwarded-Proto': 'http'})
2018-02-08T08:39:30.269826000Z     Traceback (most recent call last):
2018-02-08T08:39:30.270185000Z       File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1512, in _execute
2018-02-08T08:39:30.270417000Z         result = yield result
2018-02-08T08:39:30.270602000Z       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/pages.py", line 67, in get
2018-02-08T08:39:30.270793000Z         if user.running:
2018-02-08T08:39:30.270976000Z       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 240, in running
2018-02-08T08:39:30.271166000Z         return self.spawner.ready
2018-02-08T08:39:30.271386000Z       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 215, in spawner
2018-02-08T08:39:30.271569000Z         return self.spawners['']
2018-02-08T08:39:30.271749000Z       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 105, in __getitem__
2018-02-08T08:39:30.271926000Z         self[key] = self.spawner_factory(key)
2018-02-08T08:39:30.272101000Z       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 208, in _new_spawner
2018-02-08T08:39:30.272275000Z         spawner = spawner_class(**spawn_kwargs)
2018-02-08T08:39:30.272492000Z       File "/opt/conda/lib/python3.5/site-packages/kubespawner/spawner.py", line 80, in __init__
2018-02-08T08:39:30.272741000Z         on_failure=on_reflector_failure
2018-02-08T08:39:30.272928000Z       File "/opt/conda/lib/python3.5/site-packages/kubespawner/reflector.py", line 81, in __init__
2018-02-08T08:39:30.273176000Z         config.load_kube_config()
2018-02-08T08:39:30.273374000Z       File "/opt/conda/lib/python3.5/site-packages/kubernetes/config/kube_config.py", line 361, in load_kube_config
2018-02-08T08:39:30.273554000Z         config_persister=config_persister).load_and_set()
2018-02-08T08:39:30.273730000Z       File "/opt/conda/lib/python3.5/site-packages/kubernetes/config/kube_config.py", line 317, in _get_kube_config_loader_for_yaml_file
2018-02-08T08:39:30.273906000Z         with open(filename) as f:
2018-02-08T08:39:30.274084000Z     FileNotFoundError: [Errno 2] No such file or directory: '/root/.kube/config'
2018-02-08T08:39:30.274253000Z     
2018-02-08T08:39:30.274886000Z [E 2018-02-08 08:39:30.274 JupyterHub log:114] {
2018-02-08T08:39:30.275066000Z       "Cache-Control": "no-cache",
2018-02-08T08:39:30.275234000Z       "Accept-Encoding": "gzip, deflate",
2018-02-08T08:39:30.275489000Z       "Postman-Token": "27b5f3b1-74dc-a04f-4e5f-756272d24f4a",
2018-02-08T08:39:30.275728000Z       "X-Forwarded-For": "172.17.18.1",
2018-02-08T08:39:30.275921000Z       "Remote_user": "brent",
2018-02-08T08:39:30.276097000Z       "Connection": "close",
2018-02-08T08:39:30.276282000Z       "X-Postman-Interceptor-Id": "66a52359-4107-c526-79a2-a263ba82d0be",
2018-02-08T08:39:30.276491000Z       "X-Forwarded-Host": "10.110.18.88:30710",
2018-02-08T08:39:30.276682000Z       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36",
2018-02-08T08:39:30.276868000Z       "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
2018-02-08T08:39:30.277070000Z       "X-Forwarded-Port": "30710",
```
jupyterhub_config.py
```
import os

c = get_config()
c.JupyterHub.ip = '0.0.0.0'
c.JupyterHub.hub_ip="0.0.0.0"
c.JupyterHub.hub_port=8080
c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
c.JupyterHub.cleanup_servers = False

c.KubeSpawner.start_timeout = 60 * 5
c.KubeSpawner.singleuser_image_spec = os.environ['DOCKER_NOTEBOOK_IMAGE']

c.KubeSpawner.ip='0.0.0.0'
c.KubeSpawner.hub_connect_ip = os.environ['HUB_CONNECT_IP']
c.JupyterHub.hub_connect_ip = os.environ['HUB_CONNECT_IP']

c.KubeSpawner.singleuser_service_account = 'default'
c.KubeSpawner.user_storage_pvc_ensure = True
c.JupyterHub.allow_named_servers = True

c.KubeSpawner.cmd='/usr/bin/supervisord'
c.KubeSpawner.notebook_dir='/home/jovyan/work'
c.KubeSpawner.singleuser_working_dir='/home/jovyan/work'

c.JupyterHub.authenticator_class = 'jhub_remote_user_authenticator.remote_user_auth.RemoteUserAuthenticator'
c.JupyterHub.tornado_settings = {
    'headers': {
        'Access-Control-Allow-Origin': '*',
    },
}
# Persist hub data on volume mounted inside container
data_dir = os.environ.get('DATA_VOLUME_CONTAINER', '/data')
c.JupyterHub.cookie_secret_file = os.path.join(data_dir,'jupyterhub_cookie_secret')

c.KubeSpawner.mem_limit='2G'
```
jupyterhub.yaml
```
--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    app: jupyterhub
  name: jupyterhub
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: jupyterhub
  template: 
    metadata: 
      labels: 
        app: jupyterhub
    spec: 
      containers: 
        - env: 
            - name: DOCKER_NOTEBOOK_IMAGE
              value: "idsw-notebook:1.0.5"
            - name: LIVY_HOST
              value: "10.110.18.218"
            - name: NAMENODE
              value: "10.110.18.217"
            - name: DATANODE
              value: "10.110.18.217"
          image: "10.110.18.74:5000/idsw/jupyterhub:1.2.6"
          imagePullPolicy: Always
          name: jupyterhub
          ports: 
            - containerPort: 8000
          command: ["/bin/bash", "-c"]
          args: ["export HUB_CONNECT_IP=$(hostname -i); echo $HUB_CONNECT_IP; jupyterhub --no-ssl"]

---
kind: Service
apiVersion: v1
metadata: 
  name: jupyterhub
  labels: 
    app: jupyterhub
spec: 
  ports: 
    - name: hubhttp
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: httpapi
      port: 8080
      targetPort: 8080
  type: NodePort
  externalIPs: 
  selector: 
    app: jupyterhub
```

**Comment by xuande** [comment]
copy a `config` file into /root/.kube，The `config` file is on the kube master node.
