### ISSUE TITLE
Unauthorized basic auth attempt to kubernetes-master

### ISSUE THREAD

**Issue by clkao** [jupyterhub/kubespawner#155]
I am seeing interim errors with latest jupyterhub & kubespawner in two cases:

1. during startup: it appears hub is attempting to authenticate using basic auth and failing. killing the pod worked after hub restarted.

2. after running and working for a while, spawns started to fail with similar message. restarting also worked.

![screen shot 2018-04-03 at 8 35 56 am](https://user-images.githubusercontent.com/69736/38227674-fbce6db6-3731-11e8-8aa6-b9ac39621565.png)

It seems the service account mount `/var/run/secrets/kubernetes.io/serviceaccount` is correctly using token.  so perhaps there's weird contention when kubernetes client is initialized that somehow default to basic auth?

**Comment by clkao** [comment]
This happens while jupyterhub is loading state during initialization. killing the hub pod a few days made it working again.

```
[D 2018-04-27 09:21:36.429 JupyterHub app:1288] Loading state for XXX from db
[D 2018-04-27 09:21:36.430 JupyterHub app:1288] Loading state for YYY from db
[D 2018-04-27 09:21:36.432 JupyterHub user:191] Creating <class 'kubespawner.spawner.KubeSpawner'> for YYY:
[E 2018-04-27 09:21:36.477 JupyterHub app:1714]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1711, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1471, in initialize
        await self.init_spawners()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1293, in init_spawners
        spawner = user.spawners[name]
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 126, in __getitem__
        self[key] = self.spawner_factory(key)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 221, in _new_spawner
        spawner = spawner_class(**spawn_kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 101, in __init__
        on_failure=on_reflector_failure
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/reflector.py", line 104, in __init__
        self.start()
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/reflector.py", line 201, in start
        self._list_and_update()
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/reflector.py", line 115, in _list_and_update
        field_selector=self.field_selector
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 12291, in list_namespaced_pod
        (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 12394, in list_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 342, in request
        headers=headers)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 231, in GET
        query_params=query_params)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
        raise ApiException(http_resp=r)
    kubernetes.client.rest.ApiException: (401)
    Reason: Unauthorized
    HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Www-Authenticate': 'Basic realm="kubernetes-master"', 'Date': 'Fri, 27 Apr 2018 09:21:36 GMT', 'Content-Length': '129'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```

**Comment by consideRatio** [comment]
I have not seen this myself, and I think basic auth is about phased out at this point in time within the k8s world. I'll go ahead and close this without a more recent followup.
