### ISSUE TITLE
Config "KubeSpawner.volume_mounts"and"KubeSpawner.volumes "

### ISSUE THREAD

**Issue by IssacPan** [jupyterhub/kubespawner#175]
I have deployed jupyterhub on the OpenShift with the temporary mode :
"
c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
"
As the pod of Notebook was deleted，the user's files was destroy.
I want to  persistent the files of users.I add this columns in the jupyterhub_config.py:
"
c.KubeSpawner.user_storage_access_modes = [{'ReadWriteMany'}]
c.KubeSpawner.user_storage_capacity = '129M'
c.KubeSpawner.user_storage_class = 'glusterfs-dynamic'
c.KubeSpawner.user_storage_pvc_ensure = True
c.KubeSpawner.volume_mounts = [{'mountPath': '/home/jovyan/work', 'name': 'nbdata'}]
c.KubeSpawner.volumes = [{'name': 'nbdata'}]
"
but there is an error happened when I start the server:
"
[E 2018-05-23 07:54:29.539 JupyterHub user:427] Unhandled error starting jupyter1's server: 'set' object has no attribute 'swagger_types'
[E 2018-05-23 07:54:29.546 JupyterHub web:1621] Uncaught exception GET /hub/user/jupyter1/ (::ffff:10.130.0.1)
    HTTPServerRequest(protocol='http', host='jupyterhub-hub3.apps.openshift.localhost.com', method='GET', uri='/hub/user/jupyter1/', version='HTTP/1.1', remote_ip='::ffff:10.130.0.1')
    Traceback (most recent call last):
      File "/opt/app-root/lib/python3.5/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 747, in get
        yield self.spawn_single_user(current_user)
      File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 475, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/opt/app-root/lib/python3.5/site-packages/kubespawner/spawner.py", line 994, in start
        body=pvc
      File "/opt/rh/rh-python35/root/usr/lib64/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/opt/rh/rh-python35/root/usr/lib64/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/opt/rh/rh-python35/root/usr/lib64/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/app-root/lib/python3.5/site-packages/kubespawner/spawner.py", line 984, in asynchronize
        return method(*args, **kwargs)
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/apis/core_v1_api.py", line 6445, in create_namespaced_persistent_volume_claim
        (data) = self.create_namespaced_persistent_volume_claim_with_http_info(namespace, body, **kwargs)
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/apis/core_v1_api.py", line 6535, in create_namespaced_persistent_volume_claim_with_http_info
        collection_formats=collection_formats)
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 335, in call_api
        _preload_content, _request_timeout)
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 137, in __call_api
        body = self.sanitize_for_serialization(body)
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 214, in sanitize_for_serialization
        for key, val in iteritems(obj_dict)}
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 214, in <dictcomp>
        for key, val in iteritems(obj_dict)}
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 214, in sanitize_for_serialization
        for key, val in iteritems(obj_dict)}
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 214, in <dictcomp>
        for key, val in iteritems(obj_dict)}
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 194, in sanitize_for_serialization
        for sub_obj in obj]
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 194, in <listcomp>
        for sub_obj in obj]
      File "/opt/app-root/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 210, in sanitize_for_serialization
        for attr, _ in iteritems(obj.swagger_types)
    AttributeError: 'set' object has no attribute 'swagger_types'
"
Is there some sample for using these configs?
What's the problem in my project?

**Comment by IssacPan** [comment]
solved this problem with set
"
c.KubeSpawner.user_storage_pvc_ensure = False
"

**Comment by Ajay2307** [comment]
Hi,

Using Kubespawner How can we mount multiple PVCs in jupyter notebook?
