### ISSUE TITLE
JupyterHub 'LazyConfigValue' object has no attribute 'swagger_types'

### ISSUE THREAD

**Issue by tlkh** [jupyterhub/kubespawner#268]
Hi, I am facing issue with:

- jupyterhub==0.9.1 and 0.9.3
- jupyterhub-kubespawner==0.9.0
- kubernetes==6.0.0

I get an `Error: 'LazyConfigValue' object has no attribute 'swagger_types'` when creating notebooks from the Spawner UI. I'm also not sure how to trace down the error and Google is not helpful.

Attached below is the log output from JupyterHub pod.

```
[E 2018-10-15 02:47:14.134 JupyterHub user:477] Unhandled error starting timothy_liu's server: 'LazyConfigValue' object has no attribute 'swagger_types'
Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/pages.py", line 146, in post
        await self.spawn_single_user(user, options=options)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/conda/lib/python3.6/site-packages/kubespawner/spawner.py", line 1703, in _start
        pod,
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.6/site-packages/kubespawner/spawner.py", line 1489, in asynchronize
        return method(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 6057, in create_namespaced_pod
        (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 6142, in create_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 144, in __call_api
        body = self.sanitize_for_serialization(body)
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 213, in sanitize_for_serialization
        for key, val in iteritems(obj_dict)}
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 213, in &lt;dictcomp&gt;
        for key, val in iteritems(obj_dict)}
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 213, in sanitize_for_serialization
        for key, val in iteritems(obj_dict)}
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 213, in &lt;dictcomp&gt;
        for key, val in iteritems(obj_dict)}
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 213, in sanitize_for_serialization
        for key, val in iteritems(obj_dict)}
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 213, in &lt;dictcomp&gt;
        for key, val in iteritems(obj_dict)}
      File "/opt/conda/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 209, in sanitize_for_serialization
        for attr, _ in iteritems(obj.swagger_types)
    AttributeError: 'LazyConfigValue' object has no attribute 'swagger_types'
```

**Comment by minrk** [comment]
This is indeed an obscure error! Can you share some of your configuration in `jupyterhub_config.py`?  This looks like the result of accessing an undefined config value into a non-config field, e.g.

```python
c.KubeSpawner.extra_env = {'key': c.JupyterHub.undefined}
```

LazyConfigValue is what occurs when you access a missing item on a config object, enabling things like:

```python
c.KubeSpawner.extra_env.update({'key': 'value'})
```

But lazy values cannot be used in arbitrary locations in other objects, such as the values of a dict.

**Comment by consideRatio** [comment]
Since this issue is quite old and no followup information was provided, I'll close it as stale.
