### ISSUE TITLE
failed named server not cleaned up 

### ISSUE THREAD

**Issue by rokroskar** [jupyterhub/kubespawner#305]
I am running into problems with named servers that fail to start not getting cleaned up and having even proxy routes created for them. The sequence of events is roughly like this:

1. a `POST` request for a named server is sent to the hub; the server is spawned but fails to initialize (forcing this by using an image with the wrong entrypoint)
2. the hub `start_timeout` is set to 60 seconds - this is found in the logs after the 60 second interval:

```
[E 2019-03-06 22:38:15.090 JupyterHub user:477] Unhandled error starting rokroskar's server: pod/jupyter-rokroskar-rokroskar-2dsimple-2d2dd-2dd845f26 did not start in 60 seconds!
[E 2019-03-06 22:38:15.207 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py:619> exception=TimeoutError('pod/jupyter-rokroskar-rokroskar-2dsimple-2d2dd-2dd845f26 did not start in 60 seconds!',)> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 970, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/spawners.py", line 137, in start
        result = yield super().start(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1718, in _start
        timeout=self.start_timeout,
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 155, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-rokroskar-rokroskar-2dsimple-2d2dd-2dd845f26 did not start in 60 seconds!
```

3. Even though the spawn failed, the hub adds a route for the failed pod: 

```
[W 2019-03-06 22:56:57.700 JupyterHub proxy:324] Adding missing route for /jupyterhub/user/rokroskar/rokroskar-simple-2dd-d845f26/ (<jupyterhub.objects.Server object at 0x7f733c4815c0>)
[I 2019-03-06 22:56:57.704 JupyterHub proxy:242] Adding user rokroskar to proxy /jupyterhub/user/rokroskar/rokroskar-simple-2dd-d845f26/ => http://hub-6cc6f569d4-pvq4d:60435
[D 2019-03-06 22:56:57.704 JupyterHub proxy:686] Proxy: Fetching POST http://10.43.187.185:8001/api/routes/jupyterhub/user/rokroskar/rokroskar-simple-2dd-d845f26
```

4. The failed pod is now in a crash loop back off state but the route exists and the pod is impossible to delete via the hub. If it's deleted through k8s, the route remains. 

Relevant info: 

chart: jupyterhub-0.9-e120fda
hub: 0.9.4
kubespawner: 0.10.1

Apologies if this issue is in the wrong place (maybe it should go in the jupyterhub repo?)

**Comment by consideRatio** [comment]
I think this issue is resolved at this point with updates to JupyterHub, I'm not 100%, but I think that a pod that fails to get validated to respond by JupyterHub will be shut down.
