### ISSUE TITLE
LDAP authentication with Active Directory: ldap3.core.exceptions.LDAPSocketOpenError: invalid server address

### ISSUE THREAD

**Issue by lukas-koschmieder** [jupyterhub/kubespawner#378]
I am trying to enable LDAP auth in my JupyterHub/Kubernetes setup using this [documentation][1]. The following error message appears in the JupyterHub pod when attempting to login with my LDAP account in JupyterHub. 

[1]: https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html#example-active-directory-configuration

```
[E 2019-11-28 12:22:01.947 JupyterHub web:1788] Uncaught exception POST /hub/login?next= (XXX.XXX.XXX.XXX)
    HTTPServerRequest(protocol='http', host='10.108.219.105', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='XXX.XXX.XXX.XXX')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 483, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.6/dist-packages/ldapauthenticator/ldapauthenticator.py", line 319, in authenticate
        conn = getConnection(userdn, username, password)
      File "/usr/local/lib/python3.6/dist-packages/ldapauthenticator/ldapauthenticator.py", line 284, in getConnection
        auto_bind=self.use_ssl and ldap3.AUTO_BIND_TLS_BEFORE_BIND or ldap3.AUTO_BIND_NO_TLS,
      File "/usr/local/lib/python3.6/dist-packages/ldap3/core/connection.py", line 325, in __init__
        self.do_auto_bind()
      File "/usr/local/lib/python3.6/dist-packages/ldap3/core/connection.py", line 340, in do_auto_bind
        self.open(read_server_info=False)
      File "/usr/local/lib/python3.6/dist-packages/ldap3/strategy/sync.py", line 56, in open
        BaseStrategy.open(self, reset_usage, read_server_info)
      File "/usr/local/lib/python3.6/dist-packages/ldap3/strategy/base.py", line 151, in open
        raise LDAPSocketOpenError('invalid server address')
    ldap3.core.exceptions.LDAPSocketOpenError: invalid server address
```

I can reproduce the error via Python command line within the JupyterHub container using the same LDAP configuration:

```python
from ldap3 import Server, Connection, ALL
server = Server("XXXXX.rwth-aachen.de", port=389, get_info=ALL)
conn = Connection(server, "XXXXX,DC=rwth-aachen,DC=de", "XXXXX", auto_bind=True)
```

The above Python code will work on the Docker host proving that the LDAP configuration itself is fine. It appears that the network in the JupyterHub container is not configured for external LDAP connections: /etc/resolv.conf only contains an internal DNS server (10.XX.XX.XX). What step I am I missing?

**Comment by lukas-koschmieder** [comment]
It turned out that a misconfiguration in my firewall was causing the problem.
