### ISSUE TITLE
KeyError: 'containerStatuses' in poll()

### ISSUE THREAD

**Issue by mriedem** [jupyterhub/kubespawner#440]
## Bug description
During an unplanned load event in our hub some pods were timing out and I noticed a KeyError in the logs:

```
Sep 29 15:12:00hub-6788d79c4-mct9jhubERRORERROR 2020-09-29T20:12:00.742Z [JupyterHub user:645] Unhandled error starting 5f5118929d1395001a6aa4df's server: pod/jupyter-5f5118929d1395001a6aa4df did not start in 300 seconds!
Sep 29 15:12:00hub-6788d79c4-mct9jhubERRORERROR 2020-09-29T20:12:00.778Z [JupyterHub user:657] Failed to cleanup 5f5118929d1395001a6aa4df's server that failed to start
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 651, in spawn
        await self.stop(spawner.name)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 748, in stop
        status = await spawner.poll()
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1572, in poll
        ctr_stat = data["status"]["containerStatuses"]
    KeyError: 'containerStatuses'
    
Sep 29 15:12:00hub-6788d79c4-mct9jhubERRORERROR 2020-09-29T20:12:00.779Z [JupyterHub gen:599] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py:845> exception=TimeoutError('pod/jupyter-5f5118929d1395001a6aa4df did not start in 300 seconds!',)> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 593, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 852, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 661, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 560, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1854, in _start
        timeout=self.start_timeout,
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-5f5118929d1395001a6aa4df did not start in 300 seconds!
```

That would be here (we're using 0.13.0):

https://github.com/jupyterhub/kubespawner/blob/0.13.0/kubespawner/spawner.py#L1572

#### Expected behaviour
I don't know enough about the K8S API pod spec API and when it will or will not return `containerStatuses` but it seems that should be changed to a `.get('containerStatuses')` call.

#### Actual behaviour
KeyError during pod poll race when the pod was being deleted (timed out during spawn because we were waiting on user nodes to auto-scale up).

### How to reproduce
Since this appears to be a race it's probably not automatic to reproduce, but the best I can see would be to not have enough idle placeholders and/or user nodes and then create ~200 notebook pods in a short window (~5-10 minutes).

We were seeing 429 rate limit responses from `GET /hub/login` so we know there was a burst of login activity at the start of the event.

### Your personal set up

 - OS:

ubuntu:18.04 base docker image

 - Version:

KubeSpawner 0.13.0

 - Configuration:
n/a

**Comment by manics** [comment]
Could this be a consequence of the change to returning a dict instead of an object? https://github.com/jupyterhub/kubespawner/pull/424/files
