### ISSUE TITLE
Spawner stuck on "pending" when multiple servers are being spawned concurrently for a single user

### ISSUE THREAD

**Issue by txu0393** [jupyterhub/kubespawner#486]
### Bug description
When a single user uses the JupyterHub API to create two named servers at the same time, a lot of the time one or both of the servers get stuck at the "pending" stage, so the server never becomes ready. However, the Jupyter notebook pods are created just fine. 
As pointed out in #240, the server can't be deleted while it's pending. The only fix at this point is to restart the JupyterHub process, and then the servers show up correctly as ready and everything works fine.

#### Expected behaviour
Servers that are created at the same time should both come up successfully and reach the "ready" state eventually.

#### Actual behaviour
One or both servers get stuck in the "pending" stage and never become ready.

### How to reproduce
1. Create two servers (using the same user) at the same time.
2. Monitor the server status and notice that one or both of the servers never reaches the "ready" state

### Your personal set up
zero-to-jupyterhub 1.3.0 with minor customizations (kubernetes)

 - OS:
ubuntu 20.04
 - Version(s):
jupyterhub 1.3.0
python 3.8.5

```
alembic==1.4.3
async-generator==1.10
attrs==20.3.0
bcrypt==3.2.0
cachetools==4.1.1
certifi==2020.12.5
certipy==0.1.3
cffi==1.14.4
chardet==3.0.4
cryptography==3.2.1
entrypoints==0.3
escapism==1.0.1
google-auth==1.23.0
idna==2.10
ipython-genutils==0.2.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-telemetry==0.1.0
jupyterhub==1.3.0
jupyterhub-firstuseauthenticator==0.14.1
jupyterhub-hmacauthenticator==1.0
jupyterhub-idle-culler==1.0
jupyterhub-kubespawner==0.15.0
jupyterhub-ldapauthenticator==1.3.2
jupyterhub-ltiauthenticator==1.0.0
jupyterhub-nativeauthenticator==0.0.7
jupyterhub-tmpauthenticator==0.6
kubernetes==12.0.1
ldap3==2.8.1
Mako==1.1.3
MarkupSafe==1.1.1
mwoauth==0.3.7
nullauthenticator==1.0.0
oauthenticator==0.12.3
oauthlib==3.1.0
onetimepass==1.0.1
pamela==1.0.0
prometheus-client==0.9.0
psycopg2-binary==2.8.6
py-spy==0.3.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pycurl==7.43.0.6
PyJWT==1.7.1
PyMySQL==0.10.1
pyOpenSSL==20.0.0
pyrsistent==0.17.3
python-dateutil==2.8.1
python-editor==1.0.4
python-json-logger==2.0.1
python-slugify==4.0.1
PyYAML==5.3.1
requests==2.25.0
requests-oauthlib==1.3.0
rsa==4.6
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
six==1.15.0
SQLAlchemy==1.3.20
statsd==3.3.0
text-unidecode==1.3
tornado==6.1
traitlets==5.0.5
urllib3==1.26.2
websocket-client==0.57.0

```
</details>

- <details><summary>Configuration</summary>
KubeSpawner
Custom jupyterhub.auth.Authenticator
</details>

- <details><summary>Logs</summary>
```
hub-7cc56f6c5c-2kmqf hub [D 2021-02-25 19:53:39.572 JupyterHub spawner:1971] pod jupyter-myuser--test2 events before launch: 2021-02-25T19:53:33.624426Z [Normal] Successfully assigned mlp-runtime/jupyter-myuser--test2 to ip-10-46-138-180.ec2.internal
hub-7cc56f6c5c-2kmqf hub     2021-02-25T19:53:35Z [Normal] Pulling image "image.distro/namespace/my-notebook:1.0.3"
hub-7cc56f6c5c-2kmqf hub     2021-02-25T19:53:35Z [Normal] Successfully pulled image "image.distro/namespace/my-notebook:1.0.3" in 90.023805ms
hub-7cc56f6c5c-2kmqf hub     2021-02-25T19:53:35Z [Normal] Created container notebook
hub-7cc56f6c5c-2kmqf hub     2021-02-25T19:53:36Z [Normal] Started container notebook
hub-7cc56f6c5c-2kmqf hub [D 2021-02-25 19:53:39.579 JupyterHub spawner:1147] Polling subprocess every 30s
hub-7cc56f6c5c-2kmqf hub Traceback (most recent call last):
hub-7cc56f6c5c-2kmqf hub   File "/usr/local/lib/python3.8/dist-packages/tornado/curl_httpclient.py", line 131, in _handle_socket
hub-7cc56f6c5c-2kmqf hub     self.io_loop.add_handler(fd, self._handle_events, ioloop_event)
hub-7cc56f6c5c-2kmqf hub   File "/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py", line 147, in add_handler
hub-7cc56f6c5c-2kmqf hub     raise ValueError("fd %s added twice" % fd)
hub-7cc56f6c5c-2kmqf hub ValueError: fd 11 added twice
hub-7cc56f6c5c-2kmqf hub Traceback (most recent call last):
hub-7cc56f6c5c-2kmqf hub   File "/usr/local/lib/python3.8/dist-packages/tornado/curl_httpclient.py", line 131, in _handle_socket
hub-7cc56f6c5c-2kmqf hub     self.io_loop.add_handler(fd, self._handle_events, ioloop_event)
hub-7cc56f6c5c-2kmqf hub   File "/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py", line 147, in add_handler
hub-7cc56f6c5c-2kmqf hub     raise ValueError("fd %s added twice" % fd)
hub-7cc56f6c5c-2kmqf hub ValueError: fd 11 added twice
```
</details>

**Comment by txu0393** [comment]
It seems related to this reported issue in tornadoweb: https://github.com/tornadoweb/tornado/issues/2836

**Comment by txu0393** [comment]
To provide a conclusion to this issue:
We implemented a custom authenticator which used Tornado's AsyncHttpClient.
It did NOT play well with JupyterHub's Tornado IOLoop.
The issue was resolved when we switched to using synchronous `requests`
