### ISSUE TITLE
self._start_future still not defined when it's referenced.

### ISSUE THREAD

**Issue by athornton** [jupyterhub/kubespawner#542]
### Bug description
Even after https://github.com/jupyterhub/kubespawner/pull/511 I still get 

```
[E 2021-11-04 19:23:13.227 JupyterHub web:1789] Uncaught exception GET /nb/hub/api/users/athornton/server/progress (70.176.144.76)
    HTTPServerRequest(protocol='https', host='data-dev.lsst.cloud', method='GET', uri='/nb/hub/api/users/athornton/server/progress', version='HTTP/1.1', remote_ip='70.176.144.76')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/apihandlers/users.py", line 661, in get
        async for event in events:
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 545, in iterate_until
        yield item_future.result()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/spawner.py", line 1068, in _generate_progress
        async for event in progress:
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/spawner.py", line 2164, in progress
        start_future = self._start_future
    AttributeError: 'KubeSpawner' object has no attribute '_start_future'
```

#### Expected behaviour
I thought I would have a log devoid of `_start_future` errors.

#### Actual behaviour
See above.

### How to reproduce
Well, for me, it's "spawning a pod from my spawner menu."

### Your personal set up

z2jh on K8s (GKE, mostly).  Application configuration is in https://github.com/lsst-sqre/phalanx/ and the Hub we're building is in the `charts/nublado2` subdirectory of https://github.com/lsst-sqre/charts/

### Fix

I think this will do it: https://github.com/jupyterhub/kubespawner/pull/541

**Comment by minrk** [comment]
Closed by #541. Thanks!
