### ISSUE TITLE
Possibly harmless bug: `...Reflector object has no attribute '_stopped'`

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#585]
As part of switching to `kubernetes_asyncio` we still have an error from `reflector.py` on line 336.

### This code...

https://github.com/jupyterhub/kubespawner/blob/a93cef46e1a3847c42a7a39a2ec2f7e7b0b5c28f/kubespawner/reflector.py#L336-L338

### Leads to this error...

```python-traceback
[E 2022-03-14 10:16:36.730 JupyterHub reflector:363] Error when watching resources, retrying in 0.2s
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/reflector.py", line 336, in _watch_and_update
        if self._stopped:
    AttributeError: 'PodReflector' object has no attribute '_stopped'
```

### Diagnosis

I think we have a faulty assumption of presuming to work with a spawner object in our reflector class. Our spawner class has a `_stopped` property, but now we are in the reflector class and working with a `kubernetes_asycio.watch.Watch` class. This class [seem to have `_stop` within it though](https://github.com/tomplus/kubernetes_asyncio/blob/2d0452d52ffff8b2c0ce1f07d86bd502cfbf4529/kubernetes_asyncio/watch/watch.py#L56-L57).

### More logs from `Kubernetes namespace report` step in [this workflow run](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/runs/5535386633?check_suite_focus=true)

```python-traceback
[D 2022-03-14 10:16:36.636 JupyterHub scopes:301] Authenticated with token <APIToken('give...', service='test', client_id='jupyterhub')>
[D 2022-03-14 10:16:36.637 JupyterHub scopes:491] Checking access via scope admin:users
[D 2022-03-14 10:16:36.637 JupyterHub scopes:389] Unrestricted access to /hub/api/users/testuser-5c45acd1-d274-429a-83e1-ebc953db2879 via admin:users
[D 2022-03-14 10:16:36.638 JupyterHub roles:454] Assigning default role to User testuser-5c45acd1-d274-429a-83e1-ebc953db2879
[I 2022-03-14 10:16:36.641 JupyterHub roles:366] Adding role user for User: testuser-5c45acd1-d274-429a-83e1-ebc953db2879
[I 2022-03-14 10:16:36.645 JupyterHub log:189] 201 POST /hub/api/users/testuser-5c45acd1-d274-429a-83e1-ebc953db2879 (test@10.1.0.9) 11.92ms
[D 2022-03-14 10:16:36.678 JupyterHub scopes:301] Authenticated with token <APIToken('give...', service='test', client_id='jupyterhub')>
[D 2022-03-14 10:16:36.678 JupyterHub scopes:491] Checking access via scope servers
[D 2022-03-14 10:16:36.678 JupyterHub scopes:389] Unrestricted access to /hub/api/users/testuser-5c45acd1-d274-429a-83e1-ebc953db2879/server via servers
[D 2022-03-14 10:16:36.679 JupyterHub user:399] Creating <class 'kubespawner.spawner.KubeSpawner'> for testuser-5c45acd1-d274-429a-83e1-ebc953db2879:
[D 2022-03-14 10:16:36.683 JupyterHub base:925] Initiating spawn for testuser-5c45acd1-d274-429a-83e1-ebc953db2879
[D 2022-03-14 10:16:36.683 JupyterHub base:929] 0/64 concurrent spawns
[D 2022-03-14 10:16:36.683 JupyterHub base:934] 0 active servers
[D 2022-03-14 10:16:36.686 JupyterHub roles:477] Checking token permissions against requested role server
[I 2022-03-14 10:16:36.687 JupyterHub roles:482] Adding role server to token: <APIToken('67c1...', user='testuser-5c45acd1-d274-429a-83e1-ebc953db2879', client_id='jupyterhub')>
[I 2022-03-14 10:16:36.692 JupyterHub provider:607] Creating oauth client jupyterhub-user-testuser-5c45acd1-d274-429a-83e1-ebc953db2879
[D 2022-03-14 10:16:36.701 JupyterHub user:728] Calling Spawner.start for testuser-5c45acd1-d274-429a-83e1-ebc953db2879
[W 2022-03-14 10:16:36.710 JupyterHub base:188] Rolling back dirty objects IdentitySet([<Server(0.0.0.0:8888)>])
[I 2022-03-14 10:16:36.713 JupyterHub log:189] 202 POST /hub/api/users/testuser-5c45acd1-d274-429a-83e1-ebc953db2879/server (test@10.1.0.9) 37.05ms
[I 2022-03-14 10:16:36.713 JupyterHub spawner:2296] Attempting to create pod jupyter-testuser-2d5c45acd1-2dd274-2d429a-2d83e1-2debc953db2879, with timeout 3
[E 2022-03-14 10:16:36.730 JupyterHub reflector:363] Error when watching resources, retrying in 0.2s
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/reflector.py", line 336, in _watch_and_update
        if self._stopped:
    AttributeError: 'PodReflector' object has no attribute '_stopped'
    
# ... more errors of the same follow associated with spawning user pods
```

**Comment by consideRatio** [comment]
It seems that `_stop` is only set if `stop()` is called, which doesn't happen as part of `close()` or deleting the object etc. Due to that, I figure it may not be so good to use. I'm not feeling confident about this...
