### ISSUE TITLE
kubespwaner not rendering profile_options choices

### ISSUE THREAD

**Issue by etsyamitra** [jupyterhub/kubespawner#676]
### Bug description

kubespwaner not rendering profile_options choices, when defined as per document: https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html.

#### Expected behaviour

It should actually render the options and drive selections through hub

#### Actual behaviour

keeps erroring out with:
```    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/handlers/pages.py", line 203, in _get
        spawner_options_form = await spawner.get_options_form()
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/spawner.py", line 524, in get_options_form
        if callable(self.options_form):
      File "/usr/local/lib/python3.9/site-packages/traitlets/traitlets.py", line 686, in __get__
        return self.get(obj, cls)
      File "/usr/local/lib/python3.9/site-packages/traitlets/traitlets.py", line 648, in get
        default = obj.trait_defaults(self.name)
      File "/usr/local/lib/python3.9/site-packages/traitlets/traitlets.py", line 1752, in trait_defaults
        return self._get_trait_default_generator(names[0])(self)
      File "/usr/local/lib/python3.9/site-packages/traitlets/traitlets.py", line 1132, in __call__
        return self.func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/kubespawner/spawner.py", line 2906, in _options_form_default
        return self._render_options_form(self.profile_list)
      File "/usr/local/lib/python3.9/site-packages/kubespawner/spawner.py", line 2885, in _render_options_form
        return profile_form_template.render(profile_list=self._profile_list)
      File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
        self.environment.handle_exception()
      File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "<template>", line 54, in top-level template code
      File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
        return getattr(obj, attribute)
    jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'choices'
    ```
Have checked the spaces and tabs multiple times and looks intact.

### Your personal set up

 - OS:
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by consideRatio** [comment]
I suspect maybe you are using an too old version of kubespawner etc, as the `profile. But I consider this a support question, so please use the forum and include relevant information for people investing their time to help you such as:

1. Version of kubespawner used, and perhaps notes on how your jupyterhub is setup
2. Configuration of kubespawner provided

Also try to review your post so it looks easy to read.

From the changelog i read that this feature was introduced with KubeSpawner 4.1.0, see https://jupyterhub-kubespawner.readthedocs.io/en/latest/changelog.html.

**Comment by consideRatio** [comment]
Keeping this open, not 100% confident this is a configuration issue. Please provide your configuration and version of kubespawner used though.

**Comment by etsyamitra** [comment]
Thank you for the prompt response, it was a configuration issue indeed with spaces.
