### ISSUE TITLE
Allow Jupyterhub-kubespawner to connect to an insecure Kubernete server

### ISSUE THREAD

**Issue by madiazp** [jupyterhub/kubespawner#72]
I have a Kubernetes server with a self-signed certificate but for default the connection from the jupyterhub server to the kubernetes is refused due to an insecure connection.
 this is the kube config file:
```yaml
# cat ~/.kube/config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: $(a_big_cert)
    server: https://10.6.91.18:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: $(a_big_hash)
    client-key-data: $(a_big_hash)
```

This is the output  of the starting server:

```python
# jupyterhub -f /etc/jupyterhub/kubespawner/jupyterhub_config.py
[...]
[W 2017-08-23 18:22:49.567 JupyterHub iostream:1276] SSL Error on 9 ('10.6.91.18', 6443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)
[E 2017-08-23 18:22:49.567 JupyterHub app:1527]
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/jupyterhub/app.py", line 1524, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib64/python3.5/types.py", line 179, in throw
        return self.__wrapped.throw(tp, *rest)
      File "/usr/lib/python3.5/site-packages/jupyterhub/app.py", line 1315, in initialize
        yield self.init_spawners()
      File "/usr/lib/python3.5/site-packages/jupyterhub/app.py", line 1087, in init_spawners
        status = yield spawner.poll()
      File "/usr/lib/python3.5/site-packages/jupyterhub_kubespawner-0.5.1-py3.5.egg/kubespawner/spawner.py", line 510, in poll
        data = yield self.get_pod_info(self.pod_name)
      File "/usr/lib/python3.5/site-packages/jupyterhub_kubespawner-0.5.1-py3.5.egg/kubespawner/spawner.py", line 433, in get_pod_info
        pod_name,
      File "/usr/lib64/python3.5/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/lib64/python3.5/site-packages/tornado/gen.py", line 267, in <lambda>
        future, lambda future: callback(future.result()))
      File "/usr/lib64/python3.5/site-packages/tornado/tcpclient.py", line 174, in connect
        server_hostname=host)
      File "/usr/lib64/python3.5/site-packages/tornado/iostream.py", line 1259, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/usr/lib64/python3.5/ssl.py", line 996, in do_handshake
        self._sslobj.do_handshake()
      File "/usr/lib64/python3.5/ssl.py", line 641, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)
 ```

And kubectl don't have problem to see the cluster:

```
kubectl get nodes
NAME              STATUS    AGE
cassaca-node004   Ready     39m
cassaca-node005   Ready     44m
cassaca-node007   Ready     45m
cassaca-node008   Ready     1h
```

There is a way to tell the kubespawner that he can trust in the server? a flag or config? Thanks!

**Comment by madiazp** [comment]
I add the kubeapi server cert in the system trusted cert and it's work.

**Comment by madiazp** [comment]
yuvipanda
